// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { User } from '../../../../common/schemas-to-ts/User';
import { Commentaire } from '../../../commentaire/content-types/commentaire/commentaire';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { User_Plain } from '../../../../common/schemas-to-ts/User';
import { Commentaire_Plain } from '../../../commentaire/content-types/commentaire/commentaire';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export enum Type {
  Sf = 'SF',
  Technique = 'technique',
  Roman = 'Roman',}

export interface Livre {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    isbn?: string;
    titre?: string;
    auteur?: string;
    description?: string;
    couverture?: { data: Media };
    users: { data: User[] };
    type?: Type;
    commentaires: { data: Commentaire[] };
  };
}
export interface Livre_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  isbn?: string;
  titre?: string;
  auteur?: string;
  description?: string;
  couverture?: Media_Plain;
  users: User_Plain[];
  type?: Type;
  commentaires: Commentaire_Plain[];
}

export interface Livre_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  isbn?: string;
  titre?: string;
  auteur?: string;
  description?: string;
  couverture?: number;
  users: number[];
  type?: Type;
  commentaires: number[];
}

export interface Livre_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  isbn?: string;
  titre?: string;
  auteur?: string;
  description?: string;
  couverture?: AdminPanelRelationPropertyModification<Media_Plain>;
  users: AdminPanelRelationPropertyModification<User_Plain>;
  type?: Type;
  commentaires: AdminPanelRelationPropertyModification<Commentaire_Plain>;
}
