// Interface automatically generated by schemas-to-ts

import { Livre } from '../../../livre/content-types/livre/livre';
import { Livre_Plain } from '../../../livre/content-types/livre/livre';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Commentaire {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    auteur?: string;
    contenu?: any;
    livre?: { data: Livre };
  };
}
export interface Commentaire_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  auteur?: string;
  contenu?: any;
  livre?: Livre_Plain;
}

export interface Commentaire_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  auteur?: string;
  contenu?: any;
  livre?: number;
}

export interface Commentaire_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  auteur?: string;
  contenu?: any;
  livre?: AdminPanelRelationPropertyModification<Livre_Plain>;
}
